### ISSUE TITLE
Setting frame intervals

### ISSUE THREAD

**Issue by FallingSnow** [katyo/linux-video-rs#2]
I've figured out how to set a format (I'll list it below as it may be useful to someone else) but I cannot figure out where to set intervals/framerates. Is that currently possible?
```rust
let mut pix_format = PixFormat::from(FourCc::Mjpeg);
pix_format.set_width(1920);
pix_format.set_height(1080);
let mut format = Format::new(BufferType::VideoCapture, pix_format).unwrap();
device.set_format(&mut format).await.unwrap();
```

**Comment by katyo** [comment]
@FallingSnow Seems this feature hasn't implemented yet.
Could you try add that? PR's are welcome!

As a starting point see [`CaptureParm`](https://docs.rs/linux-video-core/0.1.0/linux_video_core/struct.CaptureParm.html), [`OutputParm`](https://docs.rs/linux-video-core/0.1.0/linux_video_core/struct.OutputParm.html), [`StreamParm`](https://docs.rs/linux-video-core/0.1.0/linux_video_core/struct.StreamParm.html), [`VIDEO_x_PARM`](https://www.kernel.org/doc/html/v4.9/media/uapi/v4l/vidioc-g-parm.html).

**Comment by katyo** [comment]
@FallingSnow I implemented such functionality today. Could you try it?

I strongly recommend you the following way to deal with controls/format/streamparams:

1. Get current value
2. Modify only that you need
3. Set modified value

**Comment by FallingSnow** [comment]
Awesome. Yes I will give it a try.

> I strongly recommend you the following way to deal with controls/format/streamparams:

I originally intended to do that but I couldn't figure out how to modify a format once I retrieved it. I'll have to look again and double check.

**Comment by FallingSnow** [comment]
Getting the frame rate returns inverted (numerator and denominator are flipped) values. I tested with `v4l2-ctl -d /dev/video0 --set-parm 60` and it reports the correct inverted value.
```rust
let time_pre_frame = device.param(BufferType::VideoCapture).await.unwrap().try_ref::<CaptureParm>().unwrap().time_per_frame();
dbg!(time_pre_frame.numerator(), time_pre_frame.denominator());

[kvm/src/video.rs:83] device.param(BufferType::VideoCapture).await.unwrap().try_ref::<CaptureParm>().unwrap().time_per_frame().numerator() = 1
[kvm/src/video.rs:83] device.param(BufferType::VideoCapture).await.unwrap().try_ref::<CaptureParm>().unwrap().time_per_frame().denominator() = 60
```

Setting the frame rate does **not** seem to work. I'm using the following code. I also tried inverting the values but that didn't work either.
```rust
let mut frame_rate = tokio_linux_video::types::Fract::default();
frame_rate.set_numerator(10);
frame_rate.set_denominator(1);
device.param(BufferType::VideoCapture).await.unwrap().try_mut::<CaptureParm>().unwrap().set_time_per_frame(frame_rate);
```

Again, setting via `v4l2-ctl -d /dev/video0 --set-parm 10` does work.

**Comment by FallingSnow** [comment]
I guess it would help if I used `device.set_format` and `device.set_param` lol Sorry about that. It's working correctly now.

So it looks like the only issue is the returned inverted frame interval fraction.

**Comment by FallingSnow** [comment]
After having realized that the method is called `time_per_frame` the 1/60 fraction makes sense.

Thanks for your quick work on this!

**Comment by Type1J** [comment]
I can't seem to get the frame rate to be set properly. Here's what I tried:
```rust
        let mut buffer_type = BufferType::VideoCapture;
        let dev = Device::open("/dev/video0").await?;


        let mut frame_rate = Fract::default();
        frame_rate.set_numerator(1).set_denominator(10);
        let mut frame_rate_parm = dev.param(buffer_type).await?;
        frame_rate_parm
            .try_mut::<CaptureParm>()
            .ok_or(anyhow::anyhow!("Could not set frame rate!"))?
            .set_time_per_frame(frame_rate);

        dev.set_param(&mut frame_rate_parm).await?;

        let val = dev.param(buffer_type).await?
            .try_mut::<CaptureParm>()
            .ok_or(anyhow::anyhow!("Could not get frame rate!"))?
            .time_per_frame();

        println!("In: {frame_rate}, Out: {val}");
```
The `printlin!()` at the end always gives: `In: 1/10, Out: 1/30`. With the `v4l` library, I can set it to 10 fps, but I want to use this library, since I have another project that will require MPlanes. I need to know how to do simple things like set fps, 1st.

**Comment by katyo** [comment]
@Type1J It looks really strange. Could you use `strace` to see `ioctl` calls?
